import defaultCreateFormOptions from "../../config/createForm.options";
import defaultCreateFormController from "../../config/createForm.controller";
import { delegateSelector } from "../../utils/delegateSelector";

// plugin function to fix the namespace/project option doesn't pass to Formio.makeRequest/Formio.makeStaticRequest
const requestPluginHandler = (requestArgs, opts) => {
  if (requestArgs?.formio) {
    const formioInstance = document.querySelector(
      `[data-formio-form-url="${requestArgs.formio.formUrl}"]`,
    );
    if (formioInstance) {
      requestArgs.formio = JSON.parse(formioInstance.dataset.formio);
      requestArgs.opts.formio = requestArgs.formio;
    }
    if (requestArgs.formio.options) {
      requestArgs.opts.base = requestArgs.formio.options.base;
      requestArgs.opts.project = requestArgs.formio.options.project;
      requestArgs.opts.namespace = requestArgs.formio.options.namespace;
      if (requestArgs.formio.options.project)
        Formio.setProjectUrl(requestArgs.formio.options.project);
      if (requestArgs.formio.options.base)
        Formio.setBaseUrl(requestArgs.formio.options.base);
    }
  }

  // the request url generated by recaptcha component doesn't honor the form options
  // https://github.com/formio/formio.js/blob/master/src/components/recaptcha/ReCaptcha.js#L114
  // hence the workaround is to inject the project id to the url
  if (requestArgs?.url?.includes(`${opts.formio.base}/recaptcha`)) {
    requestArgs.url = requestArgs.url.replace(
      `${opts.formio.base}/recaptcha`,
      `${opts.formio.projectUrl}/recaptcha`,
    );
  }
  return Promise.resolve(null);
};

const RequestPlugin = (opts) => ({
  priority: 0,
  preRequest(requestArgs) {
    return requestPluginHandler(requestArgs, opts);
  },
  preStaticRequest(requestArgs) {
    return requestPluginHandler(requestArgs, opts);
  },
  request(requestArgs) {
    return requestPluginHandler(requestArgs, opts);
  },
  staticRequest(requestArgs) {
    return requestPluginHandler(requestArgs, opts);
  },
});

const initFormioInstance = (elem, opts) => {
  // if already initiated, reject
  if (elem.dataset.formioFormUrl) return;

  // if doesn't have required options, reject
  if (!opts.envUrl || !opts.projectName || !opts.formName) {
    console.warn(
      "Require envUrl, projectName, formName to initiate the form.",
      opts,
    );
    return;
  }
  /*
   * setup config
   */
  const baseUrl = `https://${opts.envUrl.trim()}`;
  let formName = "";
  // Check if value is true/exists and is numeric
  if (opts.formRevision) {
    formName = `${opts.formName}?formRevision=${opts.formRevision}`;
  } else {
    formName = opts.formName;
  }
  const { projectName } = opts;
  const namespace = opts.namespace || `formio-${projectName}`;
  const formUrl = `${baseUrl}/${projectName}/${formName}`;

  /*
   * init formio instance
   */
  const formio = new Formio(formUrl, {
    base: baseUrl,
    project: `${baseUrl}/${projectName}`,
    namespace,
  });
  elem.dataset.formio = JSON.stringify(formio);
  elem.dataset.formioFormUrl = formUrl;

  /*
   * load formio form
   */
  const defaultOptions = {
    ...defaultCreateFormOptions,
    formio,
    namespace: formio.options.namespace,
  };

  const combinedOptions = {
    ...defaultOptions,
    // combine with hook options
    ...(typeof opts.createFormOptions === "function" &&
      opts.createFormOptions({
        ...opts,
        defaultOptions,
        elem,
      })),
  };

  // register plugin
  if (!Formio.getPlugin("requestPlugin"))
    Formio.registerPlugin(RequestPlugin(combinedOptions), "requestPlugin");

  Formio.createForm(elem, formUrl, combinedOptions).then((form) => {
    form.formio = formio;
    form.options.formio = formio;
    const callbackProps = {
      form,
      elem,
      ...opts,
    };

    if (typeof opts.createFormCallback === "function") {
      // call custom callback hook
      opts.createFormCallback(callbackProps);
    } else {
      // Force new tab on formlinks
      delegateSelector(elem, "click", "a", (e) => {
        e.target.target = "_blank";
      });
    }

    // default controller
    defaultCreateFormController(callbackProps);

    // call custom hook controller
    if (typeof opts.createFormController === "function") {
      opts.createFormController(callbackProps);
    }
  });
};

const overrideErrorForm = (renderMsg) => {
  // customise error message
  const newFunc = Formio.Form.prototype.errorForm.bind({});
  Formio.Form.prototype.errorForm = (err) => {
    if (
      (typeof err === "string" &&
        err.indexOf("Could not connect to API server") !== -1) ||
      (typeof err === "object" && err.networkError)
    ) {
      console.warn("formio error: ", err);
      return newFunc(typeof renderMsg === "function" ? renderMsg(err) : err);
    }
    return newFunc(err);
  };
};

const defaultInitFormioAction = () => {
  overrideErrorForm(
    () =>
      "This form is currently unavailable due to maintenance. Please try again later.",
  );
};

const initFormio = (cdn = null) => {
  // Init form
  Formio.icons = "fontawesome";
  if (cdn) {
    Formio.cdn.setOverrideUrl("grid", cdn);
  }
  if (premium) Formio.use(premium);

  // default callback after Formio is loaded
  if (typeof window.initFormioHook === "function") {
    window.initFormioHook({ overrideErrorForm });
  } else {
    defaultInitFormioAction();
  }

  document.querySelectorAll("[data-formio]").forEach((elem) => {
    const {
      formioProjectName,
      formioFormName,
      formioEnvUrl,
      formioPdfDownload,
      formioFormConfirmation,
      formioFormRevision,
      formioNamespace,
      formioCreateformOptions,
      formioCreateformController,
      formioCreateformCallback,
    } = elem.dataset;
    initFormioInstance(elem, {
      projectName: formioProjectName,
      formName: formioFormName,
      envUrl: formioEnvUrl,
      pdfDownload: formioPdfDownload,
      formConfirmation: formioFormConfirmation,
      formRevision: formioFormRevision,
      namespace: formioNamespace,
      createFormOptions: window[formioCreateformOptions],
      createFormController: window[formioCreateformController],
      createFormCallback: window[formioCreateformCallback],
    });
  });
};

export { initFormio, initFormioInstance };
